[toolchain]
package_manager = "yarn"
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
auction = "DfXY6aSHhYQmoHKtDLRjCrXYsc6dV2NA8aJe4tuv3SFz"
escrow = "7DcvjbnmYF4fZxNgoPKPAeRAUMictHjj1dKawgy8VGUk"
listing = "AtGsfS1vsVj1jdBrtRCrVj4Xe8Mzm1nCCb3v5niWGNVa"
marketplace = "DQGMnpU1EvMJchnp9qmo8Nfb8nmmwRuk2MT4AkSyiMQu"
nft-mint = "5ChAKGGQf6uv55gp82YHFt78mRz27jUEWUu9ZQTTKFa3"
royalty = "4iHri3AdfcHvqg6KHv4dNvZHHHfzEFQ7JbbuJ5vVf1ih"
solana_nft_marketplace = "AQh6W7hwboewQkpHjSovEZhaNJdPR6emp9jYgqt6CvXx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Force compatible proc-macro2 version
[patch.crates-io]
proc-macro2 = "=1.0.70"